### ISSUE TITLE
OTF fonts doesn't work with three.js

### ISSUE THREAD

**Issue by nkint** [gero3/facetype.js#1]
Hi!
I have some fonts that does not work with three.js. I got this error:

```
TypeError: Cannot read property 'length' of null
    at Object.THREE.Shape.Utils.triangulateShape (three.min.js:666)
    at THREE.ExtrudeGeometry.addShape (three.min.js:722)
    at THREE.ExtrudeGeometry.addShapeList (three.min.js:717)
    at THREE.ExtrudeGeometry (three.min.js:716)
    at new THREE.TextGeometry (three.min.js:
```

The ttf files works correclty, the oft not.

Any advice?

**Comment by gero3** [comment]
Do you have an example??
I actually didn't try an otf font yet.

**Comment by nkint** [comment]
Here are the files: http://we.tl/umeyBUB479
I have used code based on the official threejs extrude text example
http://threejs.org/examples/webgl_geometry_text.html

please let me know if I can add more info

**Comment by gero3** [comment]
It should work right now.
Can you test??

**Comment by nkint** [comment]
now does not produce any errors but some charachter seems to be weird..

**Comment by nkint** [comment]
( with font LeckerliOne_Regular.js ) see the attached image: 

`y k m o c`

![screen shot 2015-05-05 at 8 07 07 am](https://cloud.githubusercontent.com/assets/609314/7467674/243bc170-f2fe-11e4-8e47-589646657c80.png)

the `m` and `c` are rendered correctly, the others.. are not.

any ideas?

**Comment by gero3** [comment]
It should now work when you check reversing font direction.
![image](https://cloud.githubusercontent.com/assets/155535/7488646/61d3a58c-f3cd-11e4-85be-eabb7b508fe2.png)

**Comment by nkint** [comment]
super cool thank you!
