### ISSUE TITLE
Consecutive move commands in generated shapes

### ISSUE THREAD

**Issue by ghost** [gero3/facetype.js#18]
For SF Cartoonist Sans Bold (https://www.fontsquirrel.com/fonts/sf-cartoonist-hand) we noticed that consecutive move commands were generated in some shapes; this happens for many accented letters for this font. For example, for `ä`, the following commands are generated:

```
"m 3 0 m 540  38 q 463 -14 496 -14 q 424 31 440 -14 q 250 -23 340 -23 q 65 65 134 -23  q 3 267 3 146 q 97 484 3 390 q 315 578 191 578 q 419 559 370 578 q 471  586 439 586 q 538 465 538 586 q 534 314 538 414 q 530 163 530 214 q 540  38 530 100 m 407 410 q 363 431 408 410 q 313 442 335 442 q 192 386 243  442 q 140 259 140 330 q 166 163 140 203 q 247 115 195 115 q 404 189 328  115 q 407 410 407 262 m 553 764 q 529 701 553 728 q 468 673 504 673 q  420 697 441 673 q 399 749 399 722 q 421 810 399 785 q 479 834 442 834 q  531 813 508 834 q 553 764 553 792 m 334 746 q 306 687 334 709 q 239 666  278 666 q 193 686 213 666 q 172 732 172 705 q 203 799 172 766 q 267 831  234 831 q 334 746 334 831 z "
```

The main problem (for us) is that three.js crashes when trying to process this (see discussion in mrdoob/three.js#14929). So it would be helpful if facetype could not issue consecutive move commands. (three.js will probably have the same problem with a trailing move command.)

I don't know enough about font files, but it could well be that the font file already has this problem. So this would be a post-processing step.

In any case, if anyone else has this problem, here's a simple Python script to postprocess the generated .json file:
``` .py
#!/usr/bin/python3

import collections
import json
import sys


def process(filename):
    with open(filename, "rb") as f:
        data = json.JSONDecoder(object_pairs_hook=collections.OrderedDict).decode(f.read().decode('utf-8'))

    for ch, glyph in data['glyphs'].items():
        old = glyph['o']
        o = old.split(' ')
        i = 0
        cnt = 0
        while i < len(o):
            if o[i] == 'm' and i + 3 < len(o):
                if o[i + 3] == 'm':
                    del o[i:i+3]
                    cnt += 1
                    continue
            i += 1
        new = ' '.join(o)
        glyph['o'] = new
        if old != new:
            print('{0} {1}: {2} reduction(s)'.format(filename, ch, cnt))

    with open(filename, "wb") as f:
        f.write(json.dumps(data, separators=(',', ':'), ensure_ascii=False, indent=None).encode('utf-8'))


def main(program_name, args):
    if not args:
        print("Synax: {0} <font name>...".format(program_name))
        return -1
    for font in args:
        try:
            process(font)
        except Exception as e:
            print("Error while processing {1}: {0}".format(e, font))
            return -2
    return 0


sys.exit(main(sys.argv[0], sys.argv[1:]))
```

**Comment by gero3** [comment]
Doesn't your code throw away certain data since a move actions moves the cursors from which it starts.

**Comment by gero3** [comment]
I'm investigating this now. But it doesn't seem to generate multiple moveTo statements in a row anymore for  SF Cartoonist Hand_Bold.

[SF Cartoonist Hand_Bold.txt](https://github.com/gero3/facetype.js/files/2425020/SF.Cartoonist.Hand_Bold.txt)

**Comment by ghost** [comment]
Hmm, interesting, it looks I can only reproduce that with a version we downloaded more than three years ago. The current one doesn't seem to have the issue anymore; the old one still produces the double moveTos.

If you are interested, I can mail you the old version.
